name: Add to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    uses: AzureLocal/.github/.github/workflows/reusable-add-to-project.yml@main
    with:
      id-prefix: PLATFORM
      solution-option-id: '9c3da2ef'
    secrets:
      AZL_APP_ID: ${{ secrets.AZL_APP_ID }}
      AZL_APP_PRIVATE_KEY: ${{ secrets.AZL_APP_PRIVATE_KEY }}
